import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  renderCodingGuidelinesTemplate,
  renderPiManifestContext,
  renderPiPromptManifest,
  renderPiStartSkillOverview,
  renderPiTestDiscovery,
} from '../../manifest-agent-content/index.js';

const here = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(here, '..');

const outputs = [
  {
    path: join(projectRoot, 'src', 'generated', 'content.ts'),
    content: `// Generated by scripts/generate-content.mjs. Do not edit manually.
export const MANIFEST_CONTEXT = ${JSON.stringify(renderPiManifestContext())} as const;
`,
  },
  {
    path: join(projectRoot, 'prompts', 'manifest.md'),
    content: `${renderPiPromptManifest()}\n`,
  },
  {
    path: join(projectRoot, 'skills', '_generated_start-overview.md'),
    content: `${renderPiStartSkillOverview()}\n`,
  },
  {
    path: join(projectRoot, 'skills', '_generated_test-discovery.md'),
    content: `${renderPiTestDiscovery()}\n`,
  },
  {
    path: join(projectRoot, 'skills', '_generated_coding-guidelines.md'),
    content: `${renderCodingGuidelinesTemplate()}\n`,
  },
];

for (const output of outputs) {
  mkdirSync(dirname(output.path), { recursive: true });
  writeFileSync(output.path, output.content);
}
